<?php

/**
 * @file
 * Contains hydro_raindrop.module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function hydro_raindrop_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the hydro_raindrop module.
    case 'help.page.hydro_raindrop':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides Hydro Raindrop Multi Factor Authentication integration.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function hydro_raindrop_theme($existing, $type, $theme, $path) {
  return [
    'activate_raindrop' => [
      'variables' => ['raindrop_activated' => 'Deactivated']
    ],
  ];
}

/**
 * Implements hook_user_login().
 */
function hydro_raindrop_user_login(AccountInterface $account) {
  $route_name = \Drupal::routeMatch()->getRouteName();
  if ($route_name != 'user.reset.login') {
    $destination = Url::fromRoute('hydro_raindrop.activate')->toString();
    \Drupal::service('request_stack')->getCurrentRequest()->query->set('destination', $destination);
  }
}
